In [1]:
# Training and Test datasets
import tensorflow as tf
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [6]:
x = tf.placeholder("float", [None, 3])
y = tf.placeholder("float", [None, 3])
w = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(x,w)+b)
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, w, optimizer],
                                     feed_dict={x: x_data, y: y_data})
        print(step, cost_val,w_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={x: x_test, y: y_test}))
    print("Accuracy:", sess.run(accuracy,feed_dict={x: x_test, y: y_test}))

0 7.3378906 [[-0.8101459   0.18222982 -1.159545  ]
 [ 0.70354044 -0.41100544  1.3955647 ]
 [ 0.00252742 -1.5792412  -0.5209079 ]]
1 5.310462 [[-0.85123944  0.21916367 -1.1553853 ]
 [ 0.6000989  -0.23717473  1.3251755 ]
 [-0.12223226 -1.3923538  -0.5830356 ]]
2 4.2811127 [[-0.8813171   0.25520813 -1.161352  ]
 [ 0.5533883  -0.06525736  1.1999688 ]
 [-0.1933662  -1.2065666  -0.6976889 ]]
3 3.275794 [[-0.92033714  0.28921005 -1.1563339 ]
 [ 0.45278546  0.10198748  1.1333268 ]
 [-0.3161036  -1.0238897  -0.75762844]]
4 2.3379035 [[-0.9453574   0.31770286 -1.1598065 ]
 [ 0.41705045  0.2550788   1.0159705 ]
 [-0.3765245  -0.8539224  -0.8671748 ]]
5 1.6041301 [[-0.9715273   0.3324316  -1.1483654 ]
 [ 0.35134572  0.3620026   0.9747514 ]
 [-0.4591428  -0.7327227  -0.9057562 ]]
6 1.3851302 [[-0.97471094  0.3201068  -1.1328568 ]
 [ 0.38872516  0.3472494   0.9521252 ]
 [-0.43076783 -0.738815   -0.92803884]]
7 1.3653462 [[-0.98706365  0.31285915 -1.1132565 ]
 [ 0.3779506   0.35545316  0.954696  ]
 [

98 0.78222585 [[-1.6467956  -0.284636    0.14397064]
 [ 0.61129683  0.40068555  0.6761174 ]
 [-0.42362723 -0.53317636 -1.1408184 ]]
99 0.779388 [[-1.6525105  -0.28829437  0.15334387]
 [ 0.6125039   0.40203467  0.6735612 ]
 [-0.42259142 -0.53285164 -1.1421789 ]]
100 0.7765919 [[-1.6582001  -0.29190618  0.16264527]
 [ 0.61369836  0.40337488  0.6710265 ]
 [-0.4215511  -0.53253603 -1.1435348 ]]
101 0.77383673 [[-1.6638647  -0.29547194  0.17187567]
 [ 0.61488014  0.40470624  0.6685134 ]
 [-0.42050657 -0.5322289  -1.1448865 ]]
102 0.7711215 [[-1.6695046  -0.2989923   0.18103595]
 [ 0.6160496   0.40602824  0.66602194]
 [-0.4194576  -0.5319302  -1.1462342 ]]
103 0.76844573 [[-1.6751201  -0.30246776  0.19012691]
 [ 0.6172066   0.4073411   0.6635521 ]
 [-0.41840458 -0.5316392  -1.1475781 ]]
104 0.7658085 [[-1.6807114  -0.3058989   0.19914939]
 [ 0.6183515   0.40864426  0.661104  ]
 [-0.4173472  -0.5313559  -1.1489187 ]]
105 0.7632091 [[-1.6862788  -0.30928627  0.20810418]
 [ 0.6194842   0.409937

178 0.6400344 [[-2.0423617  -0.46853104  0.7234317 ]
 [ 0.6758322   0.47803822  0.5342296 ]
 [-0.3304194  -0.5195293  -1.2476726 ]]
179 0.63892627 [[-2.0467045  -0.4698308   0.7290743 ]
 [ 0.67632025  0.47866732  0.53311247]
 [-0.32916415 -0.51942945 -1.2490276 ]]
180 0.6378279 [[-2.0510361  -0.47111347  0.7346886 ]
 [ 0.6768024   0.47929037  0.5320073 ]
 [-0.3279078  -0.51933074 -1.2503827 ]]
181 0.636739 [[-2.0553565  -0.4723792   0.7402748 ]
 [ 0.6772789   0.47990727  0.5309139 ]
 [-0.32665017 -0.5192333  -1.2517377 ]]
182 0.6356595 [[-2.059666   -0.47362822  0.7458333 ]
 [ 0.6777496   0.4805183   0.5298322 ]
 [-0.3253915  -0.5191369  -1.2530928 ]]
183 0.6345893 [[-2.0639644  -0.47486073  0.75136435]
 [ 0.6782147   0.48112336  0.528762  ]
 [-0.32413164 -0.5190418  -1.2544477 ]]
184 0.6335282 [[-2.068252   -0.47607687  0.75686824]
 [ 0.6786743   0.48172265  0.5277031 ]
 [-0.32287073 -0.5189478  -1.2558026 ]]
185 0.632476 [[-2.072529   -0.4772769   0.7623453 ]
 [ 0.6791284   0.4823161

In [10]:
# 위와 같지만 learning_rate를 크게 잡음

x = tf.placeholder("float", [None, 3])
y = tf.placeholder("float", [None, 3])
w = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(x,w)+b)
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, w, optimizer],
                                     feed_dict={x: x_data, y: y_data})
        print(step, cost_val,w_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={x: x_test, y: y_test}))
    print("Accuracy:", sess.run(accuracy,feed_dict={x: x_test, y: y_test}))
    
    # 어느 순감 포기??

0 1.9132298 [[-1.2512381   1.5066257  -0.97119486]
 [ 1.4058604  -0.10623685 -1.9378757 ]
 [ 3.320415    0.9384699  -2.5574932 ]]
1 14.535796 [[-2.364668    2.0575562  -0.40869564]
 [-2.6957521   2.4953768  -0.4378773 ]
 [-0.7927594   3.7391458  -1.2449939 ]]
2 25.507784 [[-1.9896679   1.1200565   0.15380406]
 [-0.25825214 -1.4421225   1.0621221 ]
 [ 1.6447406  -0.01085377  0.06750572]]
3 5.5569715 [[-1.847056   1.6817126 -0.550464 ]
 [ 1.4748647  1.1811037 -3.2942212]
 [ 2.9065645  2.8002377 -4.0054092]]
4 11.675107 [[-1.6168418   0.8889984   0.01203603]
 [ 3.1022744  -1.9463062  -1.7942212 ]
 [ 4.5752006  -0.18089867 -2.6929092 ]]
5 27.114807 [[-2.741841   1.4514978  0.5745359]
 [-1.0227242  0.6786928 -0.2942214]
 [ 0.4502015  2.6316009 -1.3804095]]
6 11.9007435 [[-2.366844    0.5150142   1.1360223 ]
 [ 1.4147701  -3.2567673   1.2037446 ]
 [ 2.8876987  -1.1173756  -0.06892991]]
7 15.40695 [[-3.212436    1.0775139   1.4191145 ]
 [-2.0525365  -0.63176775  2.046052  ]
 [-0.85775423  1.6

174 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
175 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
176 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
177 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
178 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
179 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
180 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
181 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
182 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
183 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
184 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
185 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
186 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
187 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
188 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
189 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
190 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
191 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
192 nan [[nan nan nan]
 [nan

In [11]:
# 위와 같지만 learning_rate를 작게 작음

x = tf.placeholder("float", [None, 3])
y = tf.placeholder("float", [None, 3])
w = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(x,w)+b)
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, w, optimizer],
                                     feed_dict={x: x_data, y: y_data})
        print(step, cost_val,w_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={x: x_test, y: y_test}))
    print("Accuracy:", sess.run(accuracy,feed_dict={x: x_test, y: y_test}))
    
# 어느순간 cost가 같아짐 -> 학습이 이루어지지 않음

0 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
1 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
2 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
3 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
4 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
5 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
6 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
7 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]


101 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
102 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
103 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
104 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
105 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
106 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
107 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.8605855   0.89118946]
 [ 0.00720814  0.08327767 -0.6385188 ]]
108 1.2048342 [[ 0.8909307  -0.6675333   0.67865485]
 [ 0.7971496   0.860585

Prediction: [0 0 0]
Accuracy: 0.0


In [18]:
# Non-normalized inputs
import numpy as np  
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
             [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
             [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
             [816, 820.958984, 1008100, 815.48999, 819.23999],
             [819.359985, 823, 1188100, 818.469971, 818.97998],
             [819, 823, 1198100, 816, 820.450012],
             [811.700012, 815.25, 1098100, 809.780029, 813.669983],
             [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [20]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

x = tf.placeholder("float", [None, 4])
y = tf.placeholder("float", [None, 1])
w = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(x,w)+b
cost = tf.reduce_mean(tf.square(hypothesis-y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x: x_data, y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2640916500000.0 
Prediction:
 [[-1145869. ]
 [-2306410. ]
 [-1814439.4]
 [-1272009.8]
 [-1499074. ]
 [-1511686.9]
 [-1385538.8]
 [-1763973.2]]
1 Cost:  2.901524e+27 
Prediction:
 [[3.7996569e+13]
 [7.6490994e+13]
 [6.0172706e+13]
 [4.2180744e+13]
 [4.9712263e+13]
 [5.0130682e+13]
 [4.5946503e+13]
 [5.8499032e+13]]
2 Cost:  inf 
Prediction:
 [[-1.2594475e+21]
 [-2.5353974e+21]
 [-1.9945055e+21]
 [-1.3981377e+21]
 [-1.6477800e+21]
 [-1.6616491e+21]
 [-1.5229589e+21]
 [-1.9390295e+21]]
3 Cost:  inf 
Prediction:
 [[4.1746093e+28]
 [8.4039158e+28]
 [6.6110581e+28]
 [4.6343165e+28]
 [5.4617899e+28]
 [5.5077603e+28]
 [5.0480530e+28]
 [6.4271753e+28]]
4 Cost:  inf 
Prediction:
 [[-1.3837305e+36]
 [-2.7855912e+36]
 [-2.1913242e+36]
 [-1.5361067e+36]
 [-1.8103838e+36]
 [-1.8256214e+36]
 [-1.6732452e+36]
 [-2.1303738e+36]]
5 Cost:  inf 
Prediction:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]

 [nan]]
96 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
97 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
98 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
99 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
100 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
101 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
102 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
103 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
104 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
105 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
106 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
107 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]


259 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
260 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
261 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
262 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
263 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
264 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
265 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
266 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
267 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
268 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
269 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
270 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [na

435 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
436 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
437 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
438 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
439 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
440 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
441 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
442 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
443 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
444 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
445 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
446 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [na

595 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
596 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
597 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
598 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
599 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
600 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
601 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
602 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
603 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
604 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
605 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
606 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [na

750 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
751 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
752 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
753 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
754 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
755 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
756 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
757 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
758 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
759 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
760 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
761 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [na

914 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
915 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
916 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
917 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
918 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
919 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
920 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
921 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
922 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
923 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
924 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
925 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [na

1060 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1061 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1062 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1063 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1064 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1065 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1066 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1067 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1068 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1069 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1070 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1071 Cost:  nan 
Prediction:
 [[nan]
 [nan]

 [nan]]
1210 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1211 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1212 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1213 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1214 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1215 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1216 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1217 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1218 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1219 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1220 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1221 Cost:  nan 
Prediction:
 [[nan

 [nan]]
1383 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1384 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1385 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1386 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1387 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1388 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1389 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1390 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1391 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1392 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1393 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1394 Cost:  nan 
Prediction:
 [[nan

1553 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1554 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1555 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1556 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1557 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1558 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1559 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1560 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1561 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1562 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1563 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1564 Cost:  nan 
Prediction:
 [[nan]
 [nan]

1662 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1663 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1664 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1665 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1666 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1667 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1668 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1669 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1670 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1671 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1672 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1673 Cost:  nan 
Prediction:
 [[nan]
 [nan]

1757 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1758 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1759 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1760 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1761 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1762 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1763 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1764 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1765 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1766 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1767 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1768 Cost:  nan 
Prediction:
 [[nan]
 [nan]

1941 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1942 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1943 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1944 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1945 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1946 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1947 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1948 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1949 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1950 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1951 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1952 Cost:  nan 
Prediction:
 [[nan]
 [nan]

In [26]:
# 해결(min-max scale)
from sklearn.preprocessing import MinMaxScaler
tf.set_random_seed(777)  # for reproducibility

# MinMaxScaler
xy = MinMaxScaler(xy)
print(xy)

MinMaxScaler(copy=True,
             feature_range=array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02,
        8.24159973e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02,
        8.09559998e+02]]))
